display_name: Mostaqem
package_name: mostaqem

maintainer:
  name: Mazen Omar
  email: wildlifemain1@gmail.com

priority: optional

installed_size: 32000

dependencies:
  - mpv
  - libmpv-dev

section: x11

icon: linux/icon/app_icon.png

essential: false

generic_name: Mostaqem

startup_notify: true